'use client';

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  pdf,
} from '@react-pdf/renderer';
import { Analysis, MaturityDimension } from '@/lib/types';

const CYAN = '#00ACD9';
const DARK = '#07242D';
const GRAY = '#A2A2A2';
const LIGHT = '#F5F7F7';
const ORANGE = '#E36037';

const s = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: DARK },
  // Header
  headerBar: { backgroundColor: DARK, padding: 30, marginHorizontal: -40, marginTop: -40 },
  headerTitle: { fontSize: 22, fontFamily: 'Helvetica-Bold', color: '#ffffff', marginBottom: 4 },
  headerSub: { fontSize: 10, color: 'rgba(255,255,255,0.6)' },
  // Score box
  scoreRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 20, marginBottom: 20, paddingVertical: 16, paddingHorizontal: 20, backgroundColor: LIGHT, borderRadius: 4 },
  scoreNumber: { fontSize: 36, fontFamily: 'Helvetica-Bold', color: DARK },
  scoreLabel: { fontSize: 8, fontFamily: 'Helvetica', color: GRAY, textTransform: 'uppercase', letterSpacing: 2, marginTop: 2 },
  maturityBadge: { backgroundColor: CYAN, borderRadius: 12, paddingVertical: 4, paddingHorizontal: 12 },
  maturityText: { fontSize: 9, color: '#ffffff', fontFamily: 'Helvetica-Bold', textTransform: 'uppercase', letterSpacing: 1 },
  // Section
  sectionTitle: { fontSize: 14, fontFamily: 'Helvetica-Bold', color: DARK, marginBottom: 10, marginTop: 24 },
  sectionDesc: { fontSize: 9, color: GRAY, marginBottom: 12, lineHeight: 1.5 },
  // Dimension card
  dimCard: { backgroundColor: LIGHT, borderRadius: 4, padding: 12, marginBottom: 8 },
  dimHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  dimName: { fontSize: 10, fontFamily: 'Helvetica-Bold', color: DARK },
  dimScore: { fontSize: 14, fontFamily: 'Helvetica-Bold', color: CYAN },
  dimBar: { height: 3, backgroundColor: '#E5E1DB', borderRadius: 2, marginBottom: 6 },
  dimBarFill: { height: 3, backgroundColor: CYAN, borderRadius: 2 },
  dimEvidence: { fontSize: 8.5, color: GRAY, lineHeight: 1.5 },
  dimInsight: { fontSize: 8.5, fontFamily: 'Helvetica-Oblique', color: DARK, marginTop: 4 },
  // Goals / Gaps
  goalCard: { borderLeftWidth: 3, borderLeftColor: CYAN, paddingLeft: 10, paddingVertical: 6, marginBottom: 8 },
  gapCard: { borderLeftWidth: 3, borderLeftColor: ORANGE, paddingLeft: 10, paddingVertical: 6, marginBottom: 8 },
  goalTitle: { fontSize: 10, fontFamily: 'Helvetica-Bold', color: DARK },
  goalDesc: { fontSize: 8.5, color: GRAY, lineHeight: 1.5, marginTop: 2 },
  priorityBadge: { fontSize: 7, color: ORANGE, textTransform: 'uppercase', letterSpacing: 1 },
  // Tech tags
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginBottom: 12 },
  tag: { backgroundColor: DARK, borderRadius: 2, paddingVertical: 2, paddingHorizontal: 6 },
  tagText: { fontSize: 7, color: '#ffffff', fontFamily: 'Helvetica' },
  // Industry context
  contextText: { fontSize: 9, color: DARK, lineHeight: 1.6, marginBottom: 8 },
  // Offerings
  offeringCard: { backgroundColor: LIGHT, borderRadius: 4, padding: 10, marginBottom: 6 },
  offeringName: { fontSize: 10, fontFamily: 'Helvetica-Bold', color: DARK, marginBottom: 3 },
  offeringReason: { fontSize: 8.5, color: GRAY, lineHeight: 1.5 },
  // Footer
  footer: { position: 'absolute', bottom: 20, left: 40, right: 40, flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#E5E1DB', paddingTop: 8 },
  footerText: { fontSize: 7, color: GRAY },
});

function InnovationReport({ analysis, dimensions }: { analysis: Analysis; dimensions: MaturityDimension[] }) {
  const date = new Date(analysis.analyzed_at || analysis.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

  const gaps = (analysis.innovation_gaps || []).map((g) =>
    typeof g === 'string' ? { gap: g, explanation: '', priority: 'medium' } : g
  );

  return (
    <Document>
      {/* Page 1: Score + Dimensions */}
      <Page size="A4" style={s.page}>
        <View style={s.headerBar}>
          <Text style={s.headerTitle}>{analysis.company_name} — Innovation Maturity Report</Text>
          <Text style={s.headerSub}>Generated by The Beacon Innovation Platform — {date}</Text>
        </View>

        <View style={s.scoreRow}>
          <View>
            <Text style={s.scoreNumber}>{Number(analysis.overall_score)?.toFixed(1) || '—'} / 5.0</Text>
            <Text style={s.scoreLabel}>Overall Innovation Score</Text>
          </View>
          <View style={s.maturityBadge}>
            <Text style={s.maturityText}>{analysis.maturity_level || 'Pending'}</Text>
          </View>
        </View>

        <Text style={s.sectionTitle}>The 5 Innovation Dimensions</Text>

        {dimensions.map((d) => (
          <View key={d.id} style={s.dimCard}>
            <View style={s.dimHeader}>
              <Text style={s.dimName}>{d.dimension_name}</Text>
              <Text style={s.dimScore}>{Number(d.score)?.toFixed(1)}/5.0</Text>
            </View>
            <View style={s.dimBar}>
              <View style={[s.dimBarFill, { width: `${(Number(d.score) / 5) * 100}%` }]} />
            </View>
            {d.evidence && <Text style={s.dimEvidence}>{d.evidence}</Text>}
            {d.sub_scores?.insight && <Text style={s.dimInsight}>{d.sub_scores.insight}</Text>}
          </View>
        ))}

        <View style={s.footer}>
          <Text style={s.footerText}>The Beacon — Innovation Hub Antwerp</Text>
          <Text style={s.footerText}>thebeacon.eu</Text>
        </View>
      </Page>

      {/* Page 2: Goals, Gaps, Tech, Industry */}
      <Page size="A4" style={s.page}>
        {analysis.strategic_goals.length > 0 && (
          <>
            <Text style={s.sectionTitle}>Strategic Goals</Text>
            {analysis.strategic_goals.map((goal, i) => (
              <View key={i} style={s.goalCard}>
                <Text style={s.goalTitle}>{goal.goal}</Text>
                <Text style={s.goalDesc}>{goal.relevance}</Text>
              </View>
            ))}
          </>
        )}

        {gaps.length > 0 && (
          <>
            <Text style={s.sectionTitle}>Innovation Gaps</Text>
            {gaps.map((gap, i) => (
              <View key={i} style={s.gapCard}>
                <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
                  <Text style={s.goalTitle}>{gap.gap}</Text>
                  {gap.priority && <Text style={s.priorityBadge}>{gap.priority} priority</Text>}
                </View>
                {gap.explanation && <Text style={s.goalDesc}>{gap.explanation}</Text>}
              </View>
            ))}
          </>
        )}

        {analysis.technologies_detected.length > 0 && (
          <>
            <Text style={s.sectionTitle}>Technologies Detected</Text>
            <View style={s.tagRow}>
              {analysis.technologies_detected.map((tech, i) => (
                <View key={i} style={s.tag}><Text style={s.tagText}>{tech}</Text></View>
              ))}
            </View>
          </>
        )}

        {analysis.industry_context && (
          <>
            <Text style={s.sectionTitle}>Industry Context</Text>
            {analysis.industry_context.split('\n').filter(Boolean).map((p, i) => (
              <Text key={i} style={s.contextText}>{p}</Text>
            ))}
          </>
        )}

        <View style={s.footer}>
          <Text style={s.footerText}>The Beacon — Innovation Hub Antwerp</Text>
          <Text style={s.footerText}>Page 2</Text>
        </View>
      </Page>

      {/* Page 3: Recommendations */}
      <Page size="A4" style={s.page}>
        <Text style={s.sectionTitle}>How The Beacon Can Help</Text>
        {analysis.beacon_relevance && <Text style={s.sectionDesc}>{analysis.beacon_relevance}</Text>}

        {analysis.recommended_offerings.map((o, i) => (
          <View key={i} style={s.offeringCard}>
            <Text style={s.offeringName}>{i === 0 ? '⭐ ' : ''}{o.offering}</Text>
            <Text style={s.offeringReason}>{o.match_reason}</Text>
          </View>
        ))}

        <View style={{ marginTop: 30, padding: 20, backgroundColor: DARK, borderRadius: 4 }}>
          <Text style={{ fontSize: 14, fontFamily: 'Helvetica-Bold', color: '#ffffff', marginBottom: 6 }}>
            Ready to explore?
          </Text>
          <Text style={{ fontSize: 9, color: 'rgba(255,255,255,0.6)', lineHeight: 1.5 }}>
            Book a visit at The Beacon to meet your matched ecosystem companies,
            experience the coworking space, and discuss how we can support your
            innovation journey. Contact Robin Pauwels — robin@thebeacon.eu
          </Text>
        </View>

        <View style={s.footer}>
          <Text style={s.footerText}>The Beacon — Kattendijkdok-Oostkaai 22, 2000 Antwerp</Text>
          <Text style={s.footerText}>Page 3</Text>
        </View>
      </Page>
    </Document>
  );
}

export async function generateReportPDF(
  analysis: Analysis,
  dimensions: MaturityDimension[]
): Promise<Blob> {
  const doc = <InnovationReport analysis={analysis} dimensions={dimensions} />;
  const blob = await pdf(doc).toBlob();
  return blob;
}
